title: Github Blog
description: > # this means to ignore newlines until "baseurl:"
  깃헙 블로그 테스트중..
permalink: ':title/'
baseurl: "/jekyll-blog" # the subpath of your site, e.g. /blog
url: "https://gorhkd0612.github.io/jekyll-blog/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 참빛바다 # add your name
author-img: david-freeman.jpg # add your photo
about-author: Front-end Web Developer # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: gorhkd0612 # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: webdev-5 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
